// Generated by RPG Maker.
// Do not edit this file directly.
var $plugins =
[
{"name":"FourCornersBattleScreen","status":true,"description":"Alternative battle screen layout with actor portraits in the corners.","parameters":{"Bottom Left Actor":"9","Bottom Right Actor":"10","Upper Right Actor":"0","Upper Left Actor":"0"}}
];
